# Generated by Django 3.2.23 on 2023-12-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_comment_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='featured_image',
        ),
    ]
