# Generated by Django 3.2.23 on 2023-12-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_auto_20231228_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
